In [67]:
#import library

import pandas as pd
import numpy as np

In [68]:
#Membaca dan menampilkan 5 baris awal data

df = pd.read_csv('/content/sample_data/data_tugas 2 (1).csv')
df.head()

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height
0,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
1,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
2,?,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4
3,164,audi,gas,four,sedan,99.8,176.6,66.2,54.3
4,164,audi,gas,four,sedan,99.4,176.6,66.4,54.3

In [69]:
#Cek missing value dan mengubah '?' menjadi 'NaN'

df.replace('?', np.nan, inplace=True)
missing_values = df.isnull().sum()
missing_values

normalized-losses    41
make                  4
bahan-bakar          13
jumlah-pintu         18
body-style           12
wheel-bases           3
length                8
width                 5
height                4
dtype: int64

In [70]:
#Mengurutkan jumlah missing value dari yang paling banyak ke paling sedikit

missing_values.sort_values(ascending=False)

normalized-losses    41
jumlah-pintu         18
bahan-bakar          13
body-style           12
length                8
width                 5
make                  4
height                4
wheel-bases           3
dtype: int64

In [71]:
#Mengganti nilai missing value pada variabel kategorik dengan kategori baru yaitu 'unknown'

kategori_cols = ['make', 'bahan-bakar', 'jumlah-pintu', 'body-style']

for col in kategori_cols:
    df[col] = df[col].fillna('unknown')

In [72]:
#Mengisi missing value pada variabel numerik dengan rata-rata (mean)

numerik_cols = ['length', 'width', 'height']

for col in numerik_cols:
    mean_value = df[col].mean()
    df[col] = df[col].fillna(mean_value)
    print(f"Mean {col} = {mean_value}")

Mean length = 173.90253807106598
Mean width = 65.931
Mean height = 53.737313432835826

In [73]:
#

min_val = df['wheel-bases'].min()
max_val = df['wheel-bases'].max()

df['wheel-bases-normalized'] = (df['wheel-bases'] - min_val) / (max_val - min_val)

In [74]:
# Melakukan normalisasi Z-score pada variabel numerik
# mengubah data agar memiliki rata-rata 0 dan standar deviasi 1
# memudahkan perbandingan antar variabel

for col in numerik_cols:
    mean = df[col].mean()
    std = df[col].std()
    df[col + '_zscore'] = (df[col] - mean) / std

In [75]:
df

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height,wheel-bases-normalized,length_zscore,width_zscore,height_zscore
0,NaN,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8,0.058309,-0.428526,-0.867630,-2.038094
1,NaN,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8,0.058309,-0.428526,-0.867630,-2.038094
2,NaN,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4,0.230321,-0.226967,-0.204232,-0.552035
3,164,audi,gas,four,sedan,99.8,176.6,66.2,54.3,0.384840,0.226541,0.127467,0.232274
4,164,audi,gas,four,sedan,99.4,176.6,66.4,54.3,0.373178,0.226541,0.222238,0.232274
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5,0.655977,1.251132,1.406877,0.727627
201,95,volvo,gas,four,sedan,109.1,188.8,68.8,55.5,0.655977,1.251132,1.359492,0.727627
202,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5,0.655977,1.251132,1.406877,0.727627
203,95,volvo,diesel,four,sedan,109.1,188.8,68.9,55.5,0.655977,1.251132,1.406877,0.727627
204,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5,0.655977,1.251132,1.406877,0.727627

In [76]:
#Karena masih ada missing value 'NaN' pada variabel normalized-losses
#Jadi perlu mengubah tipe data 'NaN' dari string ke numerik
#Mengganti nilai hilang dengan median

df['normalized-losses'] = pd.to_numeric(df['normalized-losses'])
df['normalized-losses'] = df['normalized-losses'].fillna(df['normalized-losses'].median())

In [77]:
df

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height,wheel-bases-normalized,length_zscore,width_zscore,height_zscore
0,115.0,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8,0.058309,-0.428526,-0.867630,-2.038094
1,115.0,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8,0.058309,-0.428526,-0.867630,-2.038094
2,115.0,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4,0.230321,-0.226967,-0.204232,-0.552035
3,164.0,audi,gas,four,sedan,99.8,176.6,66.2,54.3,0.384840,0.226541,0.127467,0.232274
4,164.0,audi,gas,four,sedan,99.4,176.6,66.4,54.3,0.373178,0.226541,0.222238,0.232274
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5,0.655977,1.251132,1.406877,0.727627
201,95.0,volvo,gas,four,sedan,109.1,188.8,68.8,55.5,0.655977,1.251132,1.359492,0.727627
202,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5,0.655977,1.251132,1.406877,0.727627
203,95.0,volvo,diesel,four,sedan,109.1,188.8,68.9,55.5,0.655977,1.251132,1.406877,0.727627
204,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5,0.655977,1.251132,1.406877,0.727627

In [78]:
df.iloc[7]

normalized-losses              115.0
make                            audi
bahan-bakar                      gas
jumlah-pintu                    four
body-style                     wagon
wheel-bases                    105.8
length                    173.902538
width                           71.4
height                          55.7
wheel-bases-normalized      0.559767
length_zscore                    0.0
width_zscore                2.591516
height_zscore               0.810186
Name: 7, dtype: object